[package]
name = "bevy_graph"
version = "0.9.0"
edition = "2021"
description = "Graph data structures, as used by the Bevy game engine"
homepage = "https://bevyengine.org"
repository = "https://github.com/bevyengine/bevy"
license = "MIT OR Apache-2.0"
keywords = ["bevy"]

[dependencies]
hashbrown = "0.13.1"
slotmap = "1.0.6"
thiserror = "1.0.38"
